return {
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "catppuccin",
		},
	},
	{
		"catppuccin/nvim",
		name = "catppuccin",
		opts = {
			flavour = "mocha",
			background = {
				light = "latte",
				dark = "mocha",
			},
			transparent_background = false,
			term_colors = true,
			dim_inactive = {
				enabled = false,
				shade = "dark",
				percentage = 0.15,
			},
			styles = {
				comments = { "italic" },
				conditionals = { "italic" },
				loops = {},
				functions = {},
				keywords = {},
				strings = {},
				variables = {},
				numbers = {},
				booleans = {},
				properties = {},
				types = {},
				operators = {},
			},
			integrations = {
				-- For various plugins
				cmp = true,
				gitsigns = true,
				nvimtree = true,
				telescope = true,
				notify = true,
				mini = false,
			},
			color_overrides = {
				mocha = {
					base = "#1a1b26",
					mantle = "#1a1b26",
					crust = "#1a1b26",
					text = "#8dd1f7",
					comments = "#000000",
					subtext0 = "#8dd1f7",
					subtext1 = "#8dd1f7",
					overlay0 = "#565f89",
					overlay1 = "#565f89",
					overlay2 = "#565f89",
					surface0 = "#2596be",
					surface1 = "#2596be",
					surface2 = "#2596be",
					blue = "#2596be",
					lavender = "#8dd1f7",
					sapphire = "#8dd1f7",
					sky = "#8dd1f7",
					teal = "#8dd1f7",
					green = "#9ece6a",
					yellow = "#e0af68",
					peach = "#f7768e",
					maroon = "#f7768e",
					red = "#f7768e",
					mauve = "#ad8ee6",
					pink = "#ad8ee6",
					flamingo = "#ad8ee6",
					rosewater = "#EBF8FF",
				},
			},
		},
	},
}
