format = """
[ ](fg:#1a1b26 bg:#EBF8FF)\
$username\
[](bg:#EBF8FF fg:#1a1b26)\
[](fg:#EBF8FF bg:#2596be)\
$directory\
[](fg:#2596be bg:#EBF8FF)\
[](fg:#EBF8FF bg:#8ff5ff)\
$git_branch\
$git_status\
[](fg:#8ff5ff bg:#EBF8FF)\
[](fg:#EBF8FF bg:#204060)\
$golang\
$gradle\
$java\
$nodejs\
$rust\
$python\
[](fg:#204060 bg:#EBF8FF)\
[](fg:#EBF8FF bg:#2596be)\
$time\
[](fg:#2596be bg:#EBF8FF)\
[](fg:#EBF8FF)
$character\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# Username module with Hakker theme colors
[username]
show_always = true
style_user = "bg:#111111 fg:#8ff5ff"
style_root = "bg:#111111 fg:#EBF8FF"
format = '[$user ]($style)'
disabled = false

# Directory module with Hakker theme
[directory]
style = "bg:#2596be fg:#ffffff"
format = "[ $path ]($style)"
#truncation_length = 3
#runcation_symbol = "…/"

# Path substitutions for cleaner display
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Desktop" = "󰀾 "
"Videos" = "󰕧 "
"Public" = "󰐕 "
"Templates" = "󰏗 "

# Docker context with Hakker theme
[docker_context]
symbol = "󰡨 "
style = "bg:#EBF8FF fg:#1a1b26"
format = '[ $symbol $context ]($style)'

# Git branch with Hakker theme
[git_branch]
symbol = "󰘬"
style = "bg:#8ff5ff fg:#000000"
format = '[ $symbol $branch ]($style)'

# Git status with Hakker theme
[git_status]
style = "bg:#8ff5ff fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

# Programming language modules with Hakker theme
[golang]
symbol = "󰟓 "
style = "bg:#204060 fg:#8ff5ff"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#204060 fg:#8ff5ff"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "󰸭 "
style = "bg:#204060 fg:#8ff5ff"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "󰌞󰛦"
style = "bg:#204060 fg:#8ff5ff"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "󱘗"
style = "bg:#204060 fg:#8ff5ff"
format = '[ $symbol ($version) ]($style)'

[python]
version_format = "${raw}"
symbol = " 🐍 "
style = "bg:#204060 fg:#8ff5ff"
format = '[${symbol}${version} 󰌠($virtualenv)󰌠 ]($style)'


# Time module with Hakker theme
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2596be fg:#ffffff"
format = '[ 󰅐 $time ]($style)'

# Character module for the prompt symbol
[character]
success_symbol = '[➜](fg:#8ff5ff)'
error_symbol = '[✗](fg:#EBF8FF)'
vicmd_symbol = '[❮](fg:#2596be)'